1) Создать два списка: positive, negative.

2) В цикле использую input получить 10 чисел и если число положительное добавить в positive,
отрицательное в negative

3) Не использую min, max найти максимальный элемент в positive, и минимальный в negative

4) Вывести максимальный и минимальный элементы

5) Вывести максимальный по модулю элемент из этих двух

6) Отсортировать список positive, и создать новый список содержащий отсортированные элементы negative(copy_negative)

7) Каждому элементу copy_negative изменить знак с  '-' на '+'

8) Сравнить первый, второй, третий ... элемент positive и copy_negative и вывести одно из утверждений больше: Элемент из positive больше, Элемент из copy_negative больше, Элементы равны

In [57]:
positive =[]
negative =[]
mx = 0
mn = 0
for i in range(10):
    n = int(input(f'Введите {i+1} число:'))
    if n > 0:
        positive.append(n)
        if n > mx:
            mx = n
    elif n < 0:
        negative.append(n)
        if n < mn:
            mn = n

Введите 1 число:1
Введите 2 число:2
Введите 3 число:3
Введите 4 число:4
Введите 5 число:5
Введите 6 число:-1
Введите 7 число:-3
Введите 8 число:-2
Введите 9 число:-5
Введите 10 число:-4


In [58]:
print(mx)
print(mn)

5
-5


In [59]:
if abs(mx) > abs(mn):
    print(mx)
else:
    print(abs(mn))

5


In [60]:
positive.sort()
copy_negative = sorted(negative)

In [61]:
for i in range((len(copy_negative)-1)):
    copy_negative[i] *= -1

In [62]:
print(positive)
print(negative)
print(copy_negative)

[1, 2, 3, 4, 5]
[-1, -3, -2, -5, -4]
[5, 4, 3, 2, -1]


In [63]:
for i,j in zip(positive, copy_negative):
    if i > j: 
        print(f'Элемент из positive больше')
    elif i < j:
        print(f'Элемент из copy_negative больше')
    else:
        print('Элементы равны')

Элемент из copy_negative больше
Элемент из copy_negative больше
Элементы равны
Элемент из positive больше
Элемент из positive больше


1) Создать матрицу matrix 3Х3 ([[1,2,3], [4,5,6], [7,8,9]])(Значения лучше выбрать другие)

2) Преобразовать матрицу в np.array (np_matrix)

3) Найти максимум и минимум в матрице(попробовать фунции np.max, np.min и без их использования)

4) Что делает метод np_matrix.T

5) Вывести первую строчку матрицы

6) Вывести второй столбец матрицы(можно передавать несколько индексов np_matrix[0, 0] - выведет первый элемент)
(Лучше не использовать транспонирование)

7) Найти логарифм по основанию 10 каждого элемента матрицы(np.log10)

In [25]:
import numpy as np

In [26]:
matrix = [[3,4,9], [8,1,2], [7,5,6]]

In [27]:
np_matrix = np.array(matrix)

In [41]:
print(np.max(np_matrix))
print(np.min(np_matrix))

9
1


In [45]:
print(max(max(i) for i in matrix))
print(min(min(i) for i in matrix))

9
1


In [47]:
print(np_matrix.T) # транспонирование матрицы

[[3 8 7]
 [4 1 5]
 [9 2 6]]


In [49]:
print(matrix[0])
print(np_matrix[0])

[3, 4, 9]
[3 4 9]


In [54]:
print(np_matrix[:, 1])

[4 1 5]


In [56]:
print(np.log10(np_matrix))

[[0.47712125 0.60205999 0.95424251]
 [0.90308999 0.         0.30103   ]
 [0.84509804 0.69897    0.77815125]]
